### ISSUE TITLE
Unwanted change to NDI video format

### ISSUE THREAD

**Issue by curranjoey** [bitfocus/companion-module-birddog-ptz#104]
When using BirdDog PTZ module to control BirdDog P200 camera, firmware version A4_A5 4.5.3418-LTS. When BirdDog PTZ module enabled, after a short time, camera video format changes from 1080p50 to 1080p60 and camera stop’s transmitting image, goes to black. Cameras are going to Blackmagic ATEM 4 M/E Broadcast Studio switcher software version 8.9. Signal from camera is output SDI. When BirdDog PTZ module in Companion is disabled, does not occur.

**Comment by bryce-seifert** [comment]
This is a known bug with the BirdDog firmware and how it uses the API. You can update your camera to v5.0.057 or later to prevent this issue.
