### ISSUE TITLE
P200 connections becoming “corrupt” when installing new versions.

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-birddog-ptz#105]
Sometime in the last few betas my connections to 3 P200s have started crashing and becoming unable to connect after installing a new beta.  

I tend to install the latest betas pretty regularly especially as I get my setup ready for V3.  Somehow something has corrupted and now none of my connections to P200s connect.  Creating a new connection works.  I’ve tried reinstalling older betas but it seems the “damage” has been done.  The original programmed connection never connect then crash.  Log shows E22 connection refused. 

Similar to the issue when the module was first updated.

**Comment by bryce-seifert** [comment]
When you say "unable to connect", is that only with Companion? Are you still able to connect to the P200 web ui or via some other application?

**Comment by obcocav** [comment]
Yes still able to talk to the cams via another control software, cam control, the dashboard, etc.  the companion module just tries to load then crashes.  On another PC loaded with companion and the config imported I am able to add a new instance and it connects ok.Thanks!Sent from my iPhoneOn May 15, 2023, at 20:39, bryce ***@***.***> wrote:﻿
When you say "unable to connect", is that only with Companion? Are you still able to connect to the P200 web ui or via some other application?

**Comment by obcocav** [comment]
Hey @bryce-seifert.  I think I may have found a lead for this issue.  I finally noticed that some of my instance names previously had a space in the cam ie CAM 2 vs CAM2.  When I go to import now they default to CAM_2 with the underscore without any interaction from me.  Wondering if it is something with the instance naming in the install scripts?  
Thanks!

**Comment by bryce-seifert** [comment]
Intersting. The instance rename is happening at the Companion level, not within the module itself. But that being said, I don't think this should affect the connection. Can you send the support bundle via slack, after the module crash occurs?

**Comment by bryce-seifert** [comment]
@obcocav The latest companion beta should have the fix for the upgrade error. Let me know if this resolves the issue

**Comment by obcocav** [comment]
@bryce-seifert. 
 
Unfortunately like I mentioned I think the problem from earlier in the beta cycle is back.  I am unable to even load the GUI in the last couple of builds.  It takes 15 min or so the first time I launch companion for the “syncing” screen to appear but it never finishes loading even after a restart.  One time the GUI did pop up but all modules were listed as “unknown” status and companion crashed.  Since then I get to the sync page and it never finishes.  @Julusian @krocheck

**Comment by obcocav** [comment]
Looks like 5889 is the last usable build I can get to open

**Comment by Julusian** [comment]
could you send me your db file? `git@julusian.co.uk`

**Comment by obcocav** [comment]
Looks like its solved with the latest updates!  Thank you!
