### ISSUE TITLE
Feature Request: Exposure Compensation adjustment

### ISSUE THREAD

**Issue by GarthDB** [bitfocus/companion-module-birddog-ptz#115]
There is a preset to toggle or change the Exposure Compensation, but I can't seem to find how to change the Exposure Compensation level within the plugin. It would be nice to have presets for increasing and decreasing it.

<img width="211" alt="image" src="https://github.com/bitfocus/companion-module-birddog-ptz/assets/125516/0c124987-33e0-4d51-abe4-d16313eed077">
<img width="301" alt="image" src="https://github.com/bitfocus/companion-module-birddog-ptz/assets/125516/fc060492-64d0-42ba-9a17-62f816ba8a6d">

There is a variable for displaying the set level, but again, I can't find a way to change it.

<img width="466" alt="image" src="https://github.com/bitfocus/companion-module-birddog-ptz/assets/125516/ae03b31d-e0ad-459b-b5b8-db9debc9967c">

**Comment by GarthDB** [comment]
When the action is set to on, it shows a number input for setting the value.

This is a good workaround, but having presets to change it up or down would still be nice.

<img width="459" alt="image" src="https://github.com/bitfocus/companion-module-birddog-ptz/assets/125516/8385bc6c-dd9e-46ae-9aa3-74104db4d382">

**Comment by bryce-seifert** [comment]
@GarthDB This is now included in the Companion beta. Please give it a try, and let me know if you have any issues.
