### ISSUE TITLE
"Super Fine" PTZ speed feature added in latest (P100?) firmware -- messes up Companion

### ISSUE THREAD

**Issue by scientastic** [bitfocus/companion-module-birddog-ptz#117]
Some time ago, not sure which firmware version, I noticed a new feature in the Camera Control screen of the P100 web UI: the ability to select the speed control as either "Standard" or "Super Fine." This setting changes the acceptable range for Pan and Tilt Speed to be 0-255 instead of the standard range of 0-21 or 0-18. It is probably supported in other camera models as well.

We tend to use Super Fine in production, because we like to set it to very low speeds for slow pans, etc.

In Companion, the variables correctly report the new value that we manually set in the BirdDog UI, but we can't use Companion to adjust the values, because this module limits the values to the "standard" ranges.

For proper support, please enhance this module to support setting the "Speed Control" to either "Standard" (default) or "Super Fine" and in line with this, adjust the acceptable ranges for the Pan and Tilt variables to 0-255. I don't think it affects the Zoom speed.

I had a thought for further enhancement: use a Percent value from 0-100, and normalize it to the range appropriate for the Speed Control setting. (E.g. if "Standard" then 0-100 maps to 0-21, if "Super Fine" then 0-100 maps to 0-255.) This would be more disruptive for existing users, but would make it much easier to be consistent in how buttons work when the Speed Control mode is changed. Maybe instead: make new variables specifically for Percentage-level control, so people can use those if they want.

Thanks for the great work so far!

**Comment by bryce-seifert** [comment]
@scientastic Thanks for the report!

The latest version of the companion beta (as of last night) should have a fix that allows superfine to work. Let me know if you run into any issues!

I also added a slider to the number selection of the speed values. While it’s not quite normalizing it to a percentage, hopefully it has close to the same effect in terms of legibility. I’ll continue to think about the possibility of a separate percentage based action.
