### ISSUE TITLE
exposure controls

### ISSUE THREAD

**Issue by nottooloud** [bitfocus/companion-module-birddog-ptz#77]
P200 firmware 5.0.059 iris controls don't respond to companion-mac-arm64-2.4.0+4710-beta-05bf0507. The shutter and gain controls are erratic, responding sometimes.

**Comment by jmcc94** [comment]
Does v5.0.64 resolve the problem? Also, there is a small improvement to the birddog-ptz module in a later version of companion beta - that may help as well

**Comment by bryce-seifert** [comment]
This issue is stale. Please let us know if you are able to replicate on the latest Companion v3 beta
