### ISSUE TITLE
Pan speed control

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-birddog-ptz#84]
Hello,

is it possible programmatically to adjust or command a slower pan speed?  Would love to have a speed between “1” and “2”.  It seems the cams are capable of this (p200) as sometime it will do it on its own or when moving asynchronously.  When commanding manually though there is a large difference between 1&2.  Thanks!

**Comment by jmcc94** [comment]
@obcocav - unfortunately it looks like the speed settings are set in the camera...and are presented as a range of numbers...

We can either call them via API, or VISCA, but the are same speed on the camera.
