### ISSUE TITLE
PTZ-Tilt Speed: Speed Down issues

### ISSUE THREAD

**Issue by BBrazner** [bitfocus/companion-module-birddog-ptz#85]
I have 2.3.1 Companion on Mac M1 Mini, with BD P200 cameras running 3418-LTS FW.

PTZ-Tilt Speed: Speed Down produces erratic results, often not going lower than 9.

Note: PTZ-Tilt Speed: Speed Up works ok, as do the Pan and Zoom Speed Up/Down actions.

**Comment by bryce-seifert** [comment]
I have tested this with a P200 on the latest v3 beta. Not able to reproduce. Please let us know if this is still an issue with the new version.
