### ISSUE TITLE
Variables in triggers do not fire

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-birddog-ptz#87]
I’m trying to use a trigger to to change iris value when zoom is < or > a value.  The feedback itself updates fine but even when a condition is met it does not fire the trigger.  For example “check variable value” for zoom position > 15X then Iris 2.8 does not work even when companion. Correctly sees the zoom position as 20X.

**Comment by obcocav** [comment]
@bryce-seifert.  FWIW.  I have been using a work around by multiplying the variable by 1.  Seems to remove the degrees symbol.  So I have a dozen or so triggers to “correct” the values that fire every 3 seconds.  It works but Sure would be nice to get rid of the clutter with native ability.  Hope this helps!  Thanks for all the work you do!

**Comment by bryce-seifert** [comment]
@obcocav In v3, now in beta, zoom will now be available in as a raw integer with the `zoom_position_int` variable
