### ISSUE TITLE
Rewrite to work with Companion v3

### ISSUE THREAD

**Issue by jmcc94** [bitfocus/companion-module-birddog-ptz#88]

**Comment by Julusian** [comment]
Whats the status of this? This module is currently unusable in 3.0, it would be nice to get it at least partially working

cc @bryce-seifert

**Comment by jmcc94** [comment]
@Julusian.. It's stalled at the moment due to my time over the last couple of months.

I should hopefully have time in the coming weeks to get after this

**Comment by bryce-seifert** [comment]
v3 rewrite merged with https://github.com/bitfocus/companion-module-birddog-ptz/commit/d5f66e5c76130875119e7e98269b51792725d054
