### ISSUE TITLE
White Balance

### ISSUE THREAD

**Issue by rjurden** [bitfocus/companion-module-birddog-ptz#90]
Please add white balance to the module. This is available over VISCA. 

https://birddogtv.zohodesk.com/portal/api/kbArticles/574085000000642627/locale/en/attachments/6r81le95f4132358f4c51bd67954c5ff79410/content?portalId=edbsnfaffdf840d1eef8c81ee4ee9dfacd8a48be54e0a2e0cd1acde19c38c2612ea9e&inline=true

**Comment by jmcc94** [comment]
@rjurden What White Balance options are missing?

**Comment by bryce-seifert** [comment]
As far as I can tell, all documented options are covered by the module.

@rjurden Feel free to reopen if you can elaborate on what WB features are missing
