### ISSUE TITLE
Connection showing error state at random times

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-birddog-ptz#95]
Is anyone else having issues with the module showing an error state seemingly randomly but consistently on a P200?  I have a couple of modules that show error for what seems like know reason and this is one of them with 3 different P200s.  The commands still work even when this happens, but that is not the case for a couple of other modules so trying to track down a cause.  Feedbacks do NOT all work when the error is present.  Running 2.4.2 on Win10 with 5.0.0.94 firmware.  I was hoping the rewrite for v3 would solve but since it is still being worked on thought I'd go ahead and spend some time on this.  The other modules I'm having similar issues with are the ATEM (TVSHD) and Smartcast Vizio.  Disable and reenable fixes every time. 

Thanks!

**Comment by bryce-seifert** [comment]
I'm not sure about the other modules, but the error status has been reworked for v3, now in beta.

If you still experience with the BirdDog module in v3, feel free to re-open
