### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by Schwarztaxi** [bitfocus/companion-module-birddog-ptz#96]
Hello everyone,

I've been using the sony visca module to control our BirdDog P100, P200 and P400 cameras and it has been working wonderfully.

Since I'm using it for pan-tilt-zoom control, as well as picture adjustments, I'd love to be able to use variables to get the current values of these settings – this would make matching cameras much easier:
- Iris
- Shutter
- Gain
- WB Mode
- Blue Gain
- Red Gain

I've looked at their VISCA over IP inquiry command lists and they seem to match each other, as well as Sony's PTZs. Here are the links to their docs:
[BirdDog P100 Command List](https://birddogtv.zohodesk.com/portal/en/kb/articles/command-list-for-p100-viscaip)
[BirdDog P200 Command List](https://birddogtv.zohodesk.com/portal/en/kb/articles/viscaip-command-list-p200)
[BirdDog P400 Command List](https://birddogtv.zohodesk.com/portal/en/kb/articles/visca-command-list-for-p400-attached)
[Sony BRC-X400/X401, SRG-X400/201M2, SRG-X120/HD1M2 Command List](https://www.sony.net/Products/CameraSystem/CA/BRC_X400_SRG_X400/Technical_Document/E042100111.pdf)

Since I have no experience with programming companion modules I'm hoping that someone else can pick this up and make this module much greater than it already is :)

**Comment by krocheck** [comment]
Ok, well they can work on that here.   I don't think the Sony module implementing Birddog functionality is reasonable.

**Comment by nottooloud** [comment]
I don't know why you're asking about functions in the Sony VISCA module here. This is a discussion group for issues in the birddog module, so it not working with your P400s does seem relevant.

**Comment by bryce-seifert** [comment]
@Schwarztaxi Please give the v3 version, now in beta, a try. I should be able to connect to the P400, and actions should show actions for all cameras. 

Let me know if you still experience issues.
