### ISSUE TITLE
P400 Camera - No feedback Variables

### ISSUE THREAD

**Issue by Jonhug82** [bitfocus/companion-module-birddog-ptz#99]
I am using the BirdDog PTZ module with 4 x P400 cameras on Beta version 3.00+5759 - when I select the P400 module I am unable to receive any feedback variables from the camera. 
P400 cameras are running the latest version of firmware.

**Comment by bryce-seifert** [comment]
To clarify, is it feedback and variables that aren’t working? Or just feedback?

**Comment by Jonhug82** [comment]
When I select the P400 model the variables disappear altogether

**Comment by bryce-seifert** [comment]
This is hopefully fixes in the latest Companion 3.0 beta. Let me know if it's still an issue, as I don't have a P400 to test with.
